on:
  release:
    types: [created, published, edited]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the web-components branch
        uses: actions/checkout@v2
        with:
          ref: web-components
      - name: Generate the artifacts
        uses: skx/github-action-build@release-0.6.1
        with:
          builder: yarn pack
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'web-components-*.tar.gz'
